Add SPDX 3.0 for example7
spdx/spdx-examples pull request #85
Opened 2024-06-10 13:43 UTC by nishakm

2024-06-10 13:44 UTC, nishakm commented
@JPEWdev @kzantow

2024-06-10 14:03 UTC, maxhbr commented
This is a draft but reviews are requested?

2024-06-10 14:22 UTC, maxhbr requested changes
A rendered puml for the file (with the suggestions applied):

![example7-golang spdx json](https://github.com/spdx/spdx-examples/assets/1187050/9f3766de-033d-4084-b36e-b60ab32564af)

2024-06-10 14:22 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "type": "Software_Package",
```suggestion
      "type": "software_Package",
```

2024-06-10 14:22 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "type": "Software_File",
```suggestion
      "type": "software_File",
```

2024-06-10 14:22 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "createdUsing": [
createdUsing seems to not be valid here. At least it trips the validator.

2024-06-10 14:24 UTC, maxhbr requested changes

2024-06-10 14:24 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
This ID needs to contain something to make it unique. It can globally only be used once for an element and this seems to be wasteful. Especially if there is a new revision of this document, one would need to find a way to then create a new unique ID.

I would always recommend to add an UUID and not use real URLs as a basis.

2024-06-10 14:26 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://golang.org",
This implies, that this is the one and only entry for golang. But it contains the specific creationInfo of this document. We can't use Ids in that way.

With that you just minted the one and only entry for this organization.

We should stay away from minting elements with IDs where we do not own the corresponding domain.

2024-06-10 16:54 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "createdUsing": [
Hmm...this file was created manually, not using any tool. How do we state that here?

2024-06-10 16:54 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
How do I do that?

2024-06-10 16:57 UTC, nishakm commented
> This is a draft but reviews are requested?

It's a first pass review to iron out the obvious mistakes. I'll convert it into an actual PR after I get feedback. Thanks a bunch!

2024-06-10 17:19 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
you can generate UUIDs for example with https://www.uuidgenerator.net/

I think we are still lacking the guidelines for good spdxIds.

You could always use an urn with an UUID, e.g. `urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6`, but you would need to generate a fresh UUID for each spdxId.

2024-06-10 17:21 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "createdUsing": [
created using is a property of the creationInfo, not any element. It explains how the SPDX file was created.

2024-06-10 17:23 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "name": "example7-golang.spdx.jsonld",
I think the name of the SpdxDocument should not contain the file extension, as this should be valid and useful independent of serialization

2024-06-10 17:27 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
the implications of "all spdxIds are globally unique" makes it complicated.

2024-06-10 19:53 UTC, JPEWdev commented
#86 Will make it so that automatic validation is done on pull requests

2024-06-11 16:03 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "createdUsing": [
Isn't spdxId an `xsd:anyURI`? Wouldn't that mean using a URI rather than a URN?

2024-06-11 16:04 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
Isn't `spdxId` an `xsd:anyURI`? Wouldn't that mean using a URI and not a URN?

2024-06-11 16:38 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "spdxId": "https://github.com/spdx-examples/example7-golang.spdx.jsonld",
the internet says URN is a subset of URI. However, I'm still not sure how to format a URN. Would the ones in [this example](https://github.com/spdx/spdx-3-serialization-prototype-playground/tree/main/implementations/4) work?

2024-06-11 16:39 UTC, nishakm commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "name": "example7-golang.spdx.jsonld",
We don't have guidelines for this yet, correct?

2024-06-11 16:54 UTC, maxhbr commented on software/example7/spdx3.0/example7-golang.spdx.jsonld
> +      "name": "example7-golang.spdx.jsonld",
not sure about that. I do not think that anyone already thought about that, I was just surprised to see the extension here, in a property that is independent of serialization.

2024-06-12 15:31 UTC, nishakm commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
> +      ]
Should still have `element` here and should have all spdxIds that are in that SBOM except itself.

2024-08-01 02:22 UTC, ilans commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
> +        "urn:uuid:d8bfb4bd-f3b9-4d5e-b83d-dd48038ecfde",
remove the comma

2024-08-01 02:22 UTC, ilans commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
> +      ]
add a comma

2024-08-01 02:22 UTC, ilans commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
> +        "urn:uuid:a9f18ff3-17fa-419d-8966-abe4b992312b",
Same as above, you probably meant:
"urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8"

2024-08-01 02:22 UTC, ilans commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
<img width="1280" alt="Screen Shot 2024-07-31 at 20 33 38" src="https://github.com/user-attachments/assets/c85c1f5a-e362-4f3c-9dfa-dc1a50cbec71">

2024-08-01 02:22 UTC, ilans commented on software/example7/spdx3.0/example7-go-module.spdx.jsonld
> +        "urn:uuid:a9f18ff3-17fa-419d-8966-abe4b992312b"
Wrong spdxId. Assuming you intended to set the package spdxId, set:
"urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8"

2024-08-07 03:16 UTC, nishakm commented
@JPEWdev @maxhbr @goneall @ilans This is ready for review.

Questions from me:
- Although the person is the same, their SPDXID is different in each of the documents. I'm wondering if tools should strive to make this one SPDXID across all documents a person or organization should create or just generate UUIDs each time it executes?
- I didn't see a "BUILD_TOOL_OF" equivalent in SPDX 3, so I made a stub "Build" element and expressed that relationship as inputs and outputs.

2024-08-07 20:44 UTC, JPEWdev commented on software/example7/spdx-3.0/example7-third-party-modules.spdx.json
> +        "urn:uuid:0ae67aec-e3f7-4020-b0bc-068486068127",
This element is not in the document, which is why validation is failing. Currently, the validation doesn't handle external references, so all spdxIDs must be present in the document for it to validation; however based on what's going on here, I don't think your intention was to make this an external reference anyway

2024-08-09 14:04 UTC, nishakm commented
@JPEWdev @maxhbr @goneall @ilans This is ready for review.

Note: the validator cannot validate ExternalMap elements yet. So I will need some manual review of `example7-bin.spdx.json`.

2024-08-09 15:41 UTC, JPEWdev commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "type": "ExternalMap",
All `ExternalMap` objects need to be moved to.....

2024-08-09 15:41 UTC, JPEWdev commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      ]
... an `imports` key in this `SpdxDocument`

2024-08-20 15:56 UTC, bact requested changes

2024-08-20 15:56 UTC, bact commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "from": "urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8",
Since `urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8` is now in `imports` (as a `ExternalMap`), the validator cannot find it.

```text
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class <https://spdx.org/rdf/3.0.0/terms/Core/Element> ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:BlankNodeOrIRI ; sh:path <https://spdx.org/rdf/3.0.0/terms/Core/from> ]
	Focus Node: <urn:uuid:98dd3b3f-6b8f-49a1-88b6-628750516f1e>
	Value Node: <urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8>
	Result Path: <https://spdx.org/rdf/3.0.0/terms/Core/from>
	Message: Value does not have class <https://spdx.org/rdf/3.0.0/terms/Core/Element>
```

2024-08-20 15:56 UTC, bact commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "from": "urn:uuid:3b2939bf-fcce-4617-a06f-115168870b95",
Since `urn:uuid:3b2939bf-fcce-4617-a06f-115168870b95` is now in `imports` (as an `ExternalMap`), the validator cannot find it.

```text
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class <https://spdx.org/rdf/3.0.0/terms/Core/Element> ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:BlankNodeOrIRI ; sh:path <https://spdx.org/rdf/3.0.0/terms/Core/from> ]
	Focus Node: <urn:uuid:a7b65a78-8ed2-4b20-a91b-40f94ecdb81c>
	Value Node: <urn:uuid:3b2939bf-fcce-4617-a06f-115168870b95>
	Result Path: <https://spdx.org/rdf/3.0.0/terms/Core/from>
	Message: Value does not have class <https://spdx.org/rdf/3.0.0/terms/Core/Element>
```

2024-08-20 15:57 UTC, bact commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "from": "urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8",
In principle, this should be valid but a limitation of the validator that cannot resolve external identifiers?

2024-08-20 16:05 UTC, bact commented
>     * I didn't see a "BUILD_TOOL_OF" equivalent in SPDX 3, so I made a stub "Build" element and expressed that relationship as inputs and outputs.

`usesTool` relationship with lifecycle = `build` can be used.

See line 239 of https://github.com/spdx/using/pull/8/files
(The Annex was included in 3.0 but now moved to `using` repo in 3.0.1 temporarily for ISO-submission reason)

2024-08-20 16:16 UTC, kestewart commented
Pending validator fixes, this is expected to pass.   Waiting for merge before rechecing.

2024-08-20 16:25 UTC, kestewart commented
@nishakm - can you rebase so the checks pass (merged in Josh's fix)

2024-08-20 16:29 UTC, bact commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "from": "urn:uuid:e1877974-0aaa-48e6-931f-db4898c543f8",
Please ignore this - it should be resolved by the new validator.

2024-08-20 16:29 UTC, bact commented on software/example7/spdx-3.0/example7-bin.spdx.json
> +      "from": "urn:uuid:3b2939bf-fcce-4617-a06f-115168870b95",
Please ignore this - it should be resolved by the new validator.

2024-09-25 21:16 UTC, nishakm commented
@kestewart Done! Ready to merge

2024-09-26 13:18 UTC, goneall commented
Thanks @nishakm - I'll go ahead and merge.

We may need to do some updates once we get the validation updated to 3.0.1, but we can take care of that after we update the validation.

2024-09-26 13:18 UTC, merged